cache: yarn
language: node_js
node_js:
  - "node"
  - "7"
services:
  - docker
before_install:
  - cd regtest
  - docker-compose up -d
  - cd ..
install:
 - yarn
 - yarn global add codecov
script:
 - yarn lint
 - yarn build
 - yarn test --coverage
 - yarn start key-gen
after_success:
 - codecov
 - yarn build:docs
 - touch docs/.nojekyll
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: "docs"
  fqdn: "docs.bitname.xyz"
  on:
    node: "node"
    branch: "master"
