version: '2.0'
services:
  electrumx:
    image: "lukechilds/electrumx"
    ports:
     - "50002:50002"
     - "8000:8000"
    environment:
     - COIN=BitcoinSegwit
     - DAEMON_URL=user:password@bitcoind:12001
     - NET=regtest
    volumes:
     - ./data/electrumx-data:/data
  bitcoind:
    image: "kylemanna/bitcoind"
    ports:
     - "12001:12001"
    volumes:
     - ./data/bitcoind-data:/bitcoin
     - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
